spring:
  application:
    name: satander-dev-week-2024

  datasource:
    url: jdbc:h2:mem:sdw2024
    driver-class-name: org.h2.Driver
    username: sa
    password: '123'

  h2:
    console:
      enabled: true